#include "thread_related.h"

#include <stdio.h>
#include <time.h>

#include <windows.h>

#include "common.h"
#include "config.h"
#include "generators.h"
#include "injection.h"
#include "map.h"
#include "version.h"

int cpu_core_count_get(void)
{
	int count = 0;

	SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX *buf = nullptr;
	DWORD len = 0;

	if (!GetLogicalProcessorInformationEx(RelationProcessorCore, nullptr, &len))
		if (GetLastError() != ERROR_INSUFFICIENT_BUFFER)
			goto err;

	if (!(buf = (SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX *)malloc(len)))
		goto err;

	if (!GetLogicalProcessorInformationEx(RelationProcessorCore, buf, &len))
		goto err;

	char *ptr = (char *)buf;
	char *end = (char *)buf + len;

	while (ptr < end) {
		SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX *info = (SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX *)ptr;
		if (info->Relationship == RelationProcessorCore)
			++count;
		ptr += info->Size;
	}

err:
	free(buf);
	return count;
}

DWORD WINAPI generator_thread(LPVOID params)
{
	bool ret = true;

	GeneratorThreadArguments *args = (GeneratorThreadArguments *)params;

	Config *config = args->config;
	int *map_attempt_counter = args->map_attempt_counter;
	CRITICAL_SECTION *map_attempt_counter_cs = args->map_attempt_counter_cs;
	u32 start_time_win = args->start_time_win;
	time_t start_time_unix = args->start_time_unix;
	CRITICAL_SECTION *injection_cs = args->injection_cs;
	CRITICAL_SECTION *stdout_cs = args->stdout_cs;

	int target_map_attempt_count = config->map_count;
	bool save_maps = config->save_maps;

	while (true) {
		int map_number;

		EnterCriticalSection(map_attempt_counter_cs);
		map_number = ++*map_attempt_counter;
		LeaveCriticalSection(map_attempt_counter_cs);

		if (map_number > target_map_attempt_count)
			break;

		bool success = false;

		Map *map = nullptr;
		DynamicString *logs = nullptr;
		ConvertedMapData *converted_map_data = nullptr;

		char map_name[64];
		snprintf(map_name, sizeof(map_name), "%ld_%u_%d", (long)start_time_unix, start_time_win, map_number);
		char map_description[64];
		snprintf(map_description, sizeof(map_description), "Generated by CMG " VERSION_STR);

		if (!(map = map_init())
			|| !(logs = dynamic_string_init()))
			goto err;

		rng_state_t rng_state = start_time_unix ^ start_time_win ^ GetTickCount() ^ GetCurrentProcessId() ^ GetCurrentThreadId() ^ (rng_state_t)(usize)&rng_state;
		if (rng_state == 0)
			rng_state = 1;

		if ((config->generate_heights && !generate_heights(map, config, &rng_state, logs))
			|| (config->generate_surfaces && !generate_surfaces(map, config, &rng_state, logs))
			|| (config->generate_keeps && !generate_keeps(map, config, &rng_state, logs))
			|| (config->generate_ruins && !generate_ruins(map, config, &rng_state, logs))
			|| (config->generate_quarry_spots && !generate_quarry_spots(map, config, &rng_state, logs))
			|| (config->generate_iron_mine_spots && !generate_iron_mine_spots(map, config, &rng_state, logs))
			|| (config->generate_pitch_rig_spots && !generate_pitch_rig_spots(map, config, &rng_state, logs))
			|| (config->generate_trees && !generate_trees(map, config, &rng_state, logs))
			|| (config->generate_animals && !generate_animals(map, config, &rng_state, logs))
			|| (config->generate_shrubs && !generate_shrubs(map, config, &rng_state, logs))
			|| (config->generate_texturing && !generate_texturing(map, config, &rng_state, logs)))
			goto err;

		if (!(converted_map_data = converted_map_data_init(map, &rng_state, logs)))
			goto err;

		bool inj_ret_code;
		EnterCriticalSection(injection_cs);
		inj_ret_code = converted_map_data_inject(converted_map_data, map_name, map_description, save_maps);
		LeaveCriticalSection(injection_cs);
		if (!inj_ret_code)
			goto err;

		success = true;

err:
		EnterCriticalSection(stdout_cs);
		printf("---- %s ----\n", map_name);
		if (success) {
			printf("%s", logs->data);
		} else {
			printf("run failed\n");
			ret = false;
		}
		LeaveCriticalSection(stdout_cs);

		converted_map_data_free(converted_map_data);
		dynamic_string_free(logs);
		map_free(map);
	}

	return ret;
}
