#include "threads.h"
#include "utils.h"
#include "map.h"
#include "config.h"
#include "injection.h"
#include "generators.h"
#include <stdio.h>
#include <time.h>
#include <windows.h>

bool get_cpu_core_count(u32 *cpu_core_count)
{
	SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX *buf = NULL;
	DWORD len = 0;
	
	if (!GetLogicalProcessorInformationEx(RelationProcessorCore, NULL, &len)) {
		if (GetLastError() != ERROR_INSUFFICIENT_BUFFER) goto err;
	}
	
	if (!(buf = (SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX *)malloc(len))) goto err;
	
	if (!GetLogicalProcessorInformationEx(RelationProcessorCore, buf, &len)) goto err;
	
	u32 count = 0;
	
	u8 *ptr = (u8 *)buf;
	u8 *end = (u8 *)buf + len;
	
	while (ptr < end) {
		SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX *info = (SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX *)ptr;
		if (info->Relationship == RelationProcessorCore) count++;
		ptr += info->Size;
	}
	
	*cpu_core_count = count;
	
	return true;
	
err:
	free(buf);
	return false;
}

DWORD WINAPI generator_thread(LPVOID param)
{
	bool ret = true;
	
	GeneratorThreadArguments *args = (GeneratorThreadArguments *)param;
	
	Config *config = args->config;
	u32 *run_counter = args->run_counter;
	u32 start_time_win = args->start_time_win;
	time_t start_time_unix = args->start_time_unix;
	char *version_string = args->version_string;
	CRITICAL_SECTION *run_counter_access = args->run_counter_access;
	CRITICAL_SECTION *injection_access = args->injection_access;
	CRITICAL_SECTION *stdout_access = args->stdout_access;
	
	u32 map_count = config->map_count;
	bool save_maps = config->save_maps;
	
	while (true) {
		
		u32 map_index;
		
		EnterCriticalSection(run_counter_access);
		map_index = ++*run_counter;
		LeaveCriticalSection(run_counter_access);
		
		if (map_index > map_count) break;
		
		bool success = false;
		
		Map *map = NULL;
		DynamicString *logs = NULL;
		InjectionData *injection_data = NULL;
		
		char map_name[64];
		snprintf(map_name, sizeof(map_name), "%ld_%u_%d", (long)start_time_unix, start_time_win, map_index);
		char map_description[64];
		snprintf(map_description, sizeof(map_description), "Generated by CMG %s", version_string);
		
		if (!(map = init_map())) goto err;
		if (!(logs = init_dynamic_string())) goto err;
		
		u32 rng_state = GetTickCount() ^ start_time_win ^ start_time_unix ^ GetCurrentThreadId() ^ (u32)(usize)&rng_state;
		
		if (config->generate_heights) if (!generate_heights(map, config, &rng_state, logs)) goto err;
		if (config->generate_border) if (!generate_border(map, config, &rng_state, logs)) goto err;
		if (config->generate_grasslands) if (!generate_grasslands(map, config, &rng_state, logs)) goto err;
		if (config->generate_keeps) if (!generate_keeps(map, config, &rng_state, logs)) goto err;
		if (config->generate_quarry_spots) if (!generate_quarry_spots(map, config, &rng_state, logs)) goto err;
		if (config->generate_iron_mine_spots) if (!generate_iron_mine_spots(map, config, &rng_state, logs)) goto err;
		if (config->generate_pitch_rig_spots) if (!generate_pitch_rig_spots(map, config, &rng_state, logs)) goto err;
		if (config->generate_trees) if (!generate_trees(map, config, &rng_state, logs)) goto err;
		if (config->generate_animals) if (!generate_animals(map, config, &rng_state, logs)) goto err;
		if (config->generate_shrubs) if (!generate_shrubs(map, config, &rng_state, logs)) goto err;
		if (config->generate_texturing) if (!generate_texturing(map, config, &rng_state, logs)) goto err;
		
		if (!(injection_data = translate_map(map, &rng_state, logs))) goto err;
		
		bool inj_ret_code;
		EnterCriticalSection(injection_access);
		inj_ret_code = inject_map(injection_data, map_name, map_description, save_maps);
		LeaveCriticalSection(injection_access);
		if (!inj_ret_code) goto err;
		
		success = true;
		
		err:
		
		EnterCriticalSection(stdout_access);
		printf("---- %s ----\n", map_name);
		if (success) {
			printf("%s", logs->data);
		} else {
			printf("run failed\n");
			ret = false;
		}
		LeaveCriticalSection(stdout_access);
		
		free_injection_data(injection_data);
		free_dynamic_string(logs);
		free_map(map);
		
	}
	
	return ret;
}
